server {
    listen 80;
    
    # Root directory where the static files are stored
    root /usr/share/nginx/html;
    
    # Index file
    index index.html;
    
    # Serve static files
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    # Optionally, log the errors
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}